from enum import Enum
from typing import Dict, Tuple
from BaseClasses import Item, ItemClassification

class CSItem(Item):
    game: str = "Cultist Simulator"

class CSItemClassification(Enum):
    language = 1
    #bookreward = 2
    vaultreward = 3
    bookmorlands = 4
    bookoriflammes = 5
    bookcommon = 6
    funds = 21

item_dict: Dict[str, Tuple[ItemClassification, CSItemClassification]] = {
    # Languages
    "scholarlatin": (ItemClassification.progression, CSItemClassification.language),
    "scholargreek": (ItemClassification.progression, CSItemClassification.language),
    "scholarsanskrit": (ItemClassification.progression, CSItemClassification.language),
    "scholararamaic": (ItemClassification.progression, CSItemClassification.language),
    "scholarfucine": (ItemClassification.progression, CSItemClassification.language),
    "scholarphrygian": (ItemClassification.progression, CSItemClassification.language),
    "scholarmandaic": (ItemClassification.progression, CSItemClassification.language),
    "scholarvak": (ItemClassification.progression, CSItemClassification.language),

    """
    # Book rewards
    "accountkanishkspidersdoor_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "againstsisterhoodknot_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "apolloandmarsyas_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "asthesunhiscourse_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "bighuff_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "birdsong_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "bookextinguishedheart_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "bookofcentipede_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "bookofdissolution_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "bookofmasks_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "bookofthrones_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "bookoftrueblood_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "bookwhitecat_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "burningofunburntgod_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "burningwoman_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "catalogueofunchartedpleasures_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "ceaselesstantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "chioneatabydos_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "commandspreservationallexists_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "concursumdiaries_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "debellismurorum_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "deedsofthescarredcaptain_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "dehoris1_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "dehoris2_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "devouredtantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "dreamconspiracyskies_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "encirclingtantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "firecircletantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "fivecreations_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "flayedtantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "focusamber_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "franklinbancroftdiaries_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "furioustantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "geminiad_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "gospelzacchaeus_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "highmysterieschurchsolar_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "historyofshadowlesskings_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "howendwillbegin_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "humoursofagentleman_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "incandescenttantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "indignitiesobliviate_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "inthemountainsasupontheplain_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "introductiontohistories_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "ironbook_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "irreproachabletraditionssocietynobleendeavour_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "ivorybook_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "kitlingripe_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "knownunknowntantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "larquebinecodex_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "leoninetantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "locksmithsdream1_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "locksmithsdream2_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "locksmithsdream3_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "locksmithsdream4_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "manneralchemistspared_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "manualdeparture_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "matthiasamethystloss_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "matthiasamethystpursuit_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "matthiasamethysttransformation_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "medusaslament_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "memoryofgods_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "morphycodex_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "onthematterandthedeedsofserpents_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "onthewhite_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "onwhatiscontainedbysilver_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "orchidtransfigurations1_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "orchidtransfigurations2_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "orchidtransfigurations3_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "originsofhours_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "queensoftherivers_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "raptintheking_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "roseofhypatia_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "roseofnuriel_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "roseofwaznei_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "scarsky_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "secondglory_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "serenityofblackwood_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "sevenfoldslayingsevencoiled_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "shavenlocktantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "silverbook_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "sixlettersonnecessity_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "skeletonsongs_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "songscarapacecross_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "stumm_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "sunsetpassages_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "tantraworms_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "theskythesoul_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "thirstingtantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "thosewhodonotsleep_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "timedivision_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "travellingatnight1_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "travellingatnight2_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "travellingatnight3_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "treatiseonunderplaces_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "truecompleteasclepian_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "twentysixenticementsseventorments_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "twinserpenttantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "victoryofcrowns_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "vienneseconundra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "vinzantinscriptions_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "voyagesfo_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "wainscothistories_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "waroftheroadscensored_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "watchfultantra_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "wherehasshegone_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    "worlddoesnotweep_rewards": (ItemClassification.useful, CSItemClassification.bookreward),
    """

    # Vault rewards
    "Strathcoyne's Residence Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Forgotten Mithraeum Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Cater & Hero Limited Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "St Agnes Hospital Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Congregation of St Felix of Schüren Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),

    "Chateau Raveline Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Fermier Abbey Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Orthos Wood Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "The Vanderschaaf Collection Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Forman House Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Key-Hunter's Garret Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),

    "Cave of Candles Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Voivode's Citadel Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Grunewald's Permanent Circus Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Tower Revek Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "The Kusnetsov Endowment Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),

    "Hunter's Pits Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Snow's Keeper Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "The Eye of Ikirmawi Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Mausoleum of Wolves Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),

    "Star-Shattered Fane Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Lagun's Tomb Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Messana Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Temple of Seven Coils Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),

    "Raven Isle Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "Fort Geryk Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "The Wreck of the Christabel Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),
    "St Tentreto of the Deep Door Rewards": (ItemClassification.useful, CSItemClassification.vaultreward),


    # Common books
    "De Horis 1": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Travelling at Night 1": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Travelling at Night 2": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Six Letters on Necessity": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Locksmith's Dream 1": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Locksmith's Dream 2": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Humors of a Gentleman": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Introduction to Histories": (ItemClassification.useful, CSItemClassification.bookcommon),
    "On the White": (ItemClassification.useful, CSItemClassification.bookcommon),
    "On What is Contain By Silver": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Orchid Transfigurations 1": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Orchid Transfigurations 2": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Latin Textbook": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Greek Textbook": (ItemClassification.useful, CSItemClassification.bookcommon),
    "Sanskrit Textbook": (ItemClassification.useful, CSItemClassification.bookcommon),

    # Obtainable at Morlands only
    "War of the Roads Censored Edition": (ItemClassification.useful, CSItemClassification.bookmorlands),
    "Queens of the Rivers": (ItemClassification.useful, CSItemClassification.bookmorlands),
    "Victory of Crowns": (ItemClassification.useful, CSItemClassification.bookmorlands),
    "Kitling Ripe and the Moldywarp's Grave": (ItemClassification.useful, CSItemClassification.bookmorlands),
    "Rapt in the King": (ItemClassification.useful, CSItemClassification.bookmorlands),
    "Viennese Connundra": (ItemClassification.useful, CSItemClassification.bookmorlands),

    # Obtainable at Oriflammes only
    "STUMM!": (ItemClassification.useful, CSItemClassification.bookoriflammes),
    "De Bellis Murorum": (ItemClassification.useful, CSItemClassification.bookoriflammes),
    "True and Complete Account of the House": (ItemClassification.useful, CSItemClassification.bookoriflammes),
    "Apollo and Marsyas": (ItemClassification.useful, CSItemClassification.bookoriflammes),

    # Funds
    "Funds": (ItemClassification.filler, CSItemClassification.funds),
}