from enum import Enum
from typing import Dict, Tuple, List
from BaseClasses import Location

class CSLocation(Location):
    game: str = "Cultist Simulator"

class CSLocationClassification(Enum):
    common = 1
    vault = 2
    #book = 3

location_dict: Dict[str, Tuple[CSLocationClassification, List[str]]] = {
    # Locations where you get books
    # Obtainable at both Morlands and Oriflammes, both reachable from the start
    "De Horis 1": (CSLocationClassification.common, []),
    "Travelling at Night 1": (CSLocationClassification.common, []),
    "Travelling at Night 2": (CSLocationClassification.common, []),
    "Six Letters on Necessity": (CSLocationClassification.common, []),
    "Locksmith's Dream 1": (CSLocationClassification.common, []),
    "Locksmith's Dream 2": (CSLocationClassification.common, []),
    "Humors of a Gentleman": (CSLocationClassification.common, []),
    "Introduction to Histories": (CSLocationClassification.common, []),
    "On the White": (CSLocationClassification.common, []),
    "On What is Contain By Silver": (CSLocationClassification.common, []),
    "Orchid Transfigurations 1": (CSLocationClassification.common, []),
    "Orchid Transfigurations 2": (CSLocationClassification.common, []),
    "Latin Textbook": (CSLocationClassification.common, []),
    "Greek Textbook": (CSLocationClassification.common, []),
    "Sanskrit Textbook": (CSLocationClassification.common, []),

    # Obtainable at Morlands only
    "War of the Roads Censored Edition": (CSLocationClassification.common, []),
    "Queens of the Rivers": (CSLocationClassification.common, []),
    "Victory of Crowns": (CSLocationClassification.common, []),
    "Kitling Ripe and the Moldywarp's Grave": (CSLocationClassification.common, []),
    "Rapt in the King": (CSLocationClassification.common, []),
    "Viennese Connundra": (CSLocationClassification.common, []),

    # Obtainable at Oriflammes only
    "STUMM!": (CSLocationClassification.common, []),
    "De Bellis Murorum": (CSLocationClassification.common, []),
    "True and Complete Account of the House": (CSLocationClassification.common, []),
    "Apollo and Marsyas": (CSLocationClassification.common, []),


    # Vaults
    "Strathcoyne's Residence": (CSLocationClassification.vault, []),
    "Forgotten Mithraeum": (CSLocationClassification.vault, []),
    "Cater & Hero Limited": (CSLocationClassification.vault, []),
    "St Agnes Hospital": (CSLocationClassification.vault, []),
    "Congregation of St Felix of Schüren": (CSLocationClassification.vault, []),

    "Chateau Raveline": (CSLocationClassification.vault, []),
    "Fermier Abbey": (CSLocationClassification.vault, []),
    "Orthos Wood": (CSLocationClassification.vault, []),
    "The Vanderschaaf Collection": (CSLocationClassification.vault, []),
    "Forman House": (CSLocationClassification.vault, []),
    "Key-Hunter's Garret": (CSLocationClassification.vault, []),

    "Cave of Candles": (CSLocationClassification.vault, []),
    "Voivode's Citadel": (CSLocationClassification.vault, []),
    "Grunewald's Permanent Circus": (CSLocationClassification.vault, []),
    "Tower Revek": (CSLocationClassification.vault, []),
    "The Kusnetsov Endowment": (CSLocationClassification.vault, []),

    "Hunter's Pits": (CSLocationClassification.vault, []),
    "Snow's Keeper": (CSLocationClassification.vault, []),
    "The Eye of Ikirmawi": (CSLocationClassification.vault, []),
    "Mausoleum of Wolves": (CSLocationClassification.vault, []),

    "Star-Shattered Fane": (CSLocationClassification.vault, []),
    "Lagun's Tomb": (CSLocationClassification.vault, []),
    "Messana": (CSLocationClassification.vault, []),
    "Temple of Seven Coils": (CSLocationClassification.vault, []),

    "Raven Isle": (CSLocationClassification.vault, []),
    "Fort Geryk": (CSLocationClassification.vault, []),
    "The Wreck of the Christabel": (CSLocationClassification.vault, []),
    "St Tentreto of the Deep Door": (CSLocationClassification.vault, []),

    """
    # Locations for reading books
    "Read An Account of Kanish at the Spider Door": (CSLocationClassification.book, ["accountkanishkspidersdoor", "scholararamaic"]),
    "Read Against the Sisterhood of the Knot": (CSLocationClassification.book, ["againstsisterhoodknot", "scholargreek"]),
    "Read Apollo and Marsyas": (CSLocationClassification.book, ["apolloandmarsyas"]),
    "Read As the Sun His Course": (CSLocationClassification.book, ["asthesunhiscourse", "scholararamaic"]),
    "Read My Deeds, My Powers, My Achievements": (CSLocationClassification.book, ["bighuff", "scholarfucine"]),
    "Read Birdsong": (CSLocationClassification.book, ["birdsong", "scholarphrygian"]),
    "Read Extinguished Heart": (CSLocationClassification.book, ["extinguishedheart", "scholarmandaic"]),
    "Read Book of Centipede": (CSLocationClassification.book, ["bookofcentipede", "scholargreek"]),
    "Read Book of Dissolution": (CSLocationClassification.book, ["bookofdissolution", "scholarmandaic"]),
    "Read Book of Masks": (CSLocationClassification.book, ["bookofmasks", "scholarphrygian"]),
    "Read Book of Thrones": (CSLocationClassification.book, ["bookofthrones", "scholarphrygian"]),
    "Read Book of True Blood": (CSLocationClassification.book, ["bookoftrueblood", "scholarlatin"]),
    "Read Book of the White Cat": (CSLocationClassification.book, ["bookwhitecat", "scholarphrygian"]),
    "Read Burning of the Unburnt God": (CSLocationClassification.book, ["burningofunburntgod"]),
    "Read Burning Woman": (CSLocationClassification.book, ["burningwoman", "scholarphrygian"]),
    "Read Catalogue of Uncharted Pleasures": (CSLocationClassification.book, ["catalogueofunchartedpleasures", "scholarphrygian"]),
    "Read Ceaseless Tantra": (CSLocationClassification.book, ["ceaselesstantra", "scholarsanskrit"]),
    "Read Chione at Abydos": (CSLocationClassification.book, ["chioneatabydos"]),
    "Read Commands for the Preservation of All that Exists": (CSLocationClassification.book, ["commandspreservationallexists", "scholarmandaic"]),
    "Read Concursum Diaries": (CSLocationClassification.book, ["concursumdiaries", "scholarphrygian"]),
    "Read De Bellis Murorum": (CSLocationClassification.book, ["debellismurorum", "scholarlatin"]),
    "Read Deeds of the Scarred Captain": (CSLocationClassification.book, ["deedsofthescarredcaptain", "scholargreek"]),
    "Read De Horis 1": (CSLocationClassification.book, ["dehoris1", "scholarlatin"]),
    "Read De Horis 2": (CSLocationClassification.book, ["dehoris2", "scholarlatin"]),
    "Read Devoured Tantra": (CSLocationClassification.book, ["devouredtantra", "scholarsanskrit"]),
    "Read The Dream of the Conspiracy of the Lower Skies": (CSLocationClassification.book, ["dreamconspiracyskies"]),
    "Read Encircling Tantra": (CSLocationClassification.book, ["encirclingtantra", "scholarsanskrit"]),
    "Read Fire Circle Tantra": (CSLocationClassification.book, ["firecircletantra", "scholarsanskrit"]),
    "Read Five Creations": (CSLocationClassification.book, ["fivecreations", "scholarvak"]),
    "Read Flayed Tantra": (CSLocationClassification.book, ["flayedtantra", "scholarsanskrit"]),
    "Read The Focus of Amber": (CSLocationClassification.book, ["focusamber", "scholarmandaic"]),
    "Read Franklin Bancroft Diaries": (CSLocationClassification.book, ["franklinbancroftdiaries"]),
    "Read Furious Tantra": (CSLocationClassification.book, ["furioustantra", "scholarsanskrit"]),
    "Read The Geminiad": (CSLocationClassification.book, ["geminiad", "scholarfucine"]),
    "Read Gospel of Zacchaeus": (CSLocationClassification.book, ["gospelzacchaeus", "scholargreek"]),
    "Read High Mysteries of our Church Solar": (CSLocationClassification.book, ["highmysterieschurchsolar", "scholarfucine"]),
    "Read History of Shadowless Kings": (CSLocationClassification.book, ["historyofshadowlesskings", "scholararamaic"]),
    "Read How the End Will Begin": (CSLocationClassification.book, ["howendwillbegin", "scholarvak"]),
    "Read Humours of a Gentleman": (CSLocationClassification.book, ["humoursofagentleman"]),
    "Read Incandescent Tantra": (CSLocationClassification.book, ["incandescenttantra", "scholarsanskrit"]),
    "Read Indignities of the Obliviates": (CSLocationClassification.book, ["indignitiesobliviate", "scholarlatin"]),
    "Read In The Mountains As Upon The Plain There May Not Be A Path Where None Has Passed": (CSLocationClassification.book, ["inthemountainsasupontheplain", "scholarvak"]),
    "Read Introduction to Histories": (CSLocationClassification.book, ["introductiontohistories"]),
    "Read Iron Book": (CSLocationClassification.book, ["ironbook", "scholarfucine"]),
    "Read The Irreproachable Traditions": (CSLocationClassification.book, ["irreproachabletraditionssocietynobleendeavour", "scholarlatin"]),
    "Read Ivory Book": (CSLocationClassification.book, ["ivorybook", "scholarfucine"]),
    "Read Kitling Ripe": (CSLocationClassification.book, ["kitlingripe"]),
    "Read Known Unknown Tantra": (CSLocationClassification.book, ["knownunknowntantra", "scholarsanskrit"]),
    "Read Larquebine Codex": (CSLocationClassification.book, ["larquebinecodex", "scholarphrygian"]),
    "Read Leonine Tantra": (CSLocationClassification.book, ["leoninetantra", "scholarsanskrit"]),
    "Read Locksmith's Dream 1": (CSLocationClassification.book, ["locksmithsdream1"]),
    "Read Locksmith's Dream 2": (CSLocationClassification.book, ["locksmithsdream2"]),
    "Read Locksmith's Dream 3": (CSLocationClassification.book, ["locksmithsdream3"]),
    "Read Locksmith's Dream 4": (CSLocationClassification.book, ["locksmithsdream4"]),
    "Read Manner in Which the Alchemist was Spared": (CSLocationClassification.book, ["manneralchemistspared", "scholarvak"]),
    "Read Manual Departure": (CSLocationClassification.book, ["manualdeparture", "scholarvak"]),
    "Read Matthias & Amethyst Imago: Loss": (CSLocationClassification.book, ["matthiasamethystloss", "scholararamaic"]),
    "Read Matthias & Amethyst Imago: Pursuit": (CSLocationClassification.book, ["matthiasamethystpursuit", "scholararamaic"]),
    "Read Matthias & Amethyst Imago: Transformation": (CSLocationClassification.book, ["matthiasamethysttransformation", "scholararamaic"]),
    "Read Medusa's Lament": (CSLocationClassification.book, ["medusaslament", "scholargreek"]),
    "Read In Memory of Gods": (CSLocationClassification.book, ["memoryofgods", "scholarfucine"]),
    "Read Morphy Codex": (CSLocationClassification.book, ["morphycodex", "scholararamaic"]),
    "Read On the Matter and the Deeds of Serpents": (CSLocationClassification.book, ["onthematterandthedeedsofserpents", "scholarvak"]),
    "Read On the White": (CSLocationClassification.book, ["onthewhite"]),
    "Read On What is Contained by Silver": (CSLocationClassification.book, ["onwhatiscontainedbysilver", "scholargreek"]),
    "Read Orchid Transfigurations 1": (CSLocationClassification.book, ["orchidtransfigurations1", "scholarlatin"]),
    "Read Orchid Transfigurations 2": (CSLocationClassification.book, ["orchidtransfigurations2", "scholarlatin"]),
    "Read Orchid Transfigurations 3": (CSLocationClassification.book, ["orchidtransfigurations3", "scholarlatin"]),
    "Read Origins of Hours": (CSLocationClassification.book, ["originsofhours", "scholarvak"]),
    "Read Queens of the Rivers": (CSLocationClassification.book, ["queensoftherivers"]),
    "Read Rapt in the King": (CSLocationClassification.book, ["raptintheking"]),
    "Read Rose of Hypatia": (CSLocationClassification.book, ["roseofhypatia", "scholargreek"]),
    "Read Rose of Nuriel": (CSLocationClassification.book, ["roseofnuriel", "scholargreek"]),
    "Read Rose of Waznei": (CSLocationClassification.book, ["roseofwaznei", "scholargreek"]),
    "Read The Scar in the Sky": (CSLocationClassification.book, ["scarsky", "scholarfucine"]),
    "Read A Second Glory": (CSLocationClassification.book, ["secondglory", "scholarmandaic"]),
    "Read Serenity of Blackwood": (CSLocationClassification.book, ["serenityofblackwood", "scholargreek"]),
    "Read The Sevenfold Slaying of the Seven Coiled": (CSLocationClassification.book, ["sevenfoldslayingsevencoiled", "scholarfucine"]),
    "Read Shaven Lock Tantra": (CSLocationClassification.book, ["shavenlocktantra", "scholarsanskrit"]),
    "Read Silver Book": (CSLocationClassification.book, ["silverbook", "scholarfucine"]),
    "Read Six Letters on Necessity": (CSLocationClassification.book, ["sixlettersonnecessity"]),
    "Read Skeleton Songs": (CSLocationClassification.book, ["skeletonsongs"]),
    "Read Songs of the Carapace Cross": (CSLocationClassification.book, ["songscarapacecross", "scholarmandaic"]),
    "Watch STUMM!": (CSLocationClassification.book, ["stumm"]),
    "Read Sunset Passages": (CSLocationClassification.book, ["sunsetpassages", "scholarlatin"]),
    "Read Tantra of Worms": (CSLocationClassification.book, ["tantraworms", "scholarsanskrit"]),
    "Read The Sky The Soul": (CSLocationClassification.book, ["theskythesoul", "scholararamaic"]),
    "Read The Thirsting Tantra": (CSLocationClassification.book, ["thirstingtantra", "scholarsanskrit"]),
    "Read Those Who Do Not Sleep": (CSLocationClassification.book, ["thosewhodonotsleep"]),
    "Read A Time of Division": (CSLocationClassification.book, ["timedivision", "scholarmandaic"]),
    "Read Travelling at Night 1": (CSLocationClassification.book, ["travellingatnight1"]),
    "Read Travelling at Night 2": (CSLocationClassification.book, ["travellingatnight2"]),
    "Read Travelling at Night 3": (CSLocationClassification.book, ["travellingatnight3"]),
    "Read Treatise on Underplaces": (CSLocationClassification.book, ["treatiseonunderplaces"]),
    "Read True and Complete Accounting": (CSLocationClassification.book, ["truecompleteasclepian", "scholargreek"]),
    "Read Twenty-Six Enticements Seven Torments": (CSLocationClassification.book, ["twentysixenticementsseventorments", "scholarfucine"]),
    "Read Twin Serpent Tantra": (CSLocationClassification.book, ["twinserpenttantra", "scholarsanskrit"]),
    "Read Victory of Crowns": (CSLocationClassification.book, ["victoryofcrowns"]),
    "Read Viennese Conundra": (CSLocationClassification.book, ["vienneseconundra"]),
    "Read Vinzant Inscriptions": (CSLocationClassification.book, ["vinzantinscriptions", "scholarphrygian"]),
    "Read Voyages of Ferninshun of Oreol": (CSLocationClassification.book, ["voyagesfo", "scholarfucine"]),
    "Read Wainscot Histories": (CSLocationClassification.book, ["wainscothistories"]),
    "Read War of the Roads": (CSLocationClassification.book, ["waroftheroadscensored"]),
    "Read Watchful Tantra": (CSLocationClassification.book, ["watchfultantra", "scholarsanskrit"]),
    "Read Where Has She Gone": (CSLocationClassification.book, ["wherehasshegone", "scholarvak"]),
    "Read The World Does Not Weep": (CSLocationClassification.book, ["worlddoesnotweep", "scholararamaic"]),
    """
    # Languages
    "Learn Latin via Textbook": (CSLocationClassification.book, ["textbooklatin"]),
    "Learn Greek via Textbook": (CSLocationClassification.book, ["textbookgreek"]),
    "Learn Sanskrit via Textbook": (CSLocationClassification.book, ["textbooksanskrit"]),
    "Learn Aramaic via Textbook": (CSLocationClassification.book, ["textbookaramaic"]),
    "Learn Fucine via Textbook": (CSLocationClassification.book, ["textbookfucine", "scholarlatin"]),
    "Learn Phrygian via Textbook": (CSLocationClassification.book, ["textbookphrygian", "scholargreek"]),
    "Learn Mandaic via Textbook": (CSLocationClassification.book, ["textbookmandaic", "scholararamaic"]),
    "Learn Vak via Textbook": (CSLocationClassification.book, ["textbookvak", "scholarsanskrit"]),
}
    
